export const DEFAULT_AVATAR = 'https://api.dicebear.com/7.x/avataaars/svg?seed=default';

export const DEFAULT_USERS = [
    {
        id: 9001,
        userName: 'Alice Chen',
        userEmail: 'alice@quickchat.demo',
        professionalTitle: 'Senior Software Engineer',
        location: 'San Francisco, CA',
        joinDate: '2023-01-15',
        bio: 'Passionate about building scalable systems and open-source software. Love contributing to OSS projects and speaking at tech conferences.',
        portfolio: 'https://alicechen.dev',
        skills: 'TypeScript, React, Node.js, AWS, GraphQL',
        hobbies: 'Hiking, Photography, Open Source',
        instagram: '@alicechen_dev',
        profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AliceChen',
        publishedPostCount: 12,
    },
    {
        id: 9002,
        userName: 'Bob Martinez',
        userEmail: 'bob@quickchat.demo',
        professionalTitle: 'Full Stack Developer',
        location: 'Austin, TX',
        joinDate: '2023-03-20',
        bio: 'Building the future of web with modern JavaScript frameworks. Speaker, blogger, and coffee enthusiast.',
        portfolio: 'https://bobmartinez.io',
        skills: 'Angular, Spring Boot, Docker, PostgreSQL, Kubernetes',
        hobbies: 'Gaming, Cooking, Tech Blogging',
        instagram: '@bob_codes',
        profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BobMartinez',
        publishedPostCount: 8,
    },
];

export const DEFAULT_POSTS = [
    {
        creatorName: 'Alice Chen',
        creatorEmail: 'alice@quickchat.demo',
        creatorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AliceChen',
        content: '🚀 AI-assisted coding is no longer the future — it\'s today. Tools like GitHub Copilot are genuinely changing how fast engineers ship features. Embracing AI workflows has cut my boilerplate time in half. #AI #SoftwareEngineering',
        likeCount: 142,
        dislikeCount: 4,
        createdDate: '2026-04-22',
    },
    {
        creatorName: 'Bob Martinez',
        creatorEmail: 'bob@quickchat.demo',
        creatorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BobMartinez',
        content: '💡 Hot take: Microservices are not for every team. If your org has fewer than 20 engineers, a well-structured monolith will outperform a distributed system on every metric. Keep it simple until you truly need to scale. #Architecture #Backend',
        likeCount: 98,
        dislikeCount: 12,
        createdDate: '2026-04-21',
    },
    {
        creatorName: 'Alice Chen',
        creatorEmail: 'alice@quickchat.demo',
        creatorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AliceChen',
        content: '🔐 Security reminder: Stop storing plain-text passwords. Use bcrypt or argon2. Enable MFA everywhere. Rotate secrets regularly. The number of breaches caused by basic hygiene failures is staggering. #Cybersecurity #DevSecOps',
        likeCount: 211,
        dislikeCount: 1,
        createdDate: '2026-04-20',
    },
    {
        creatorName: 'Bob Martinez',
        creatorEmail: 'bob@quickchat.demo',
        creatorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BobMartinez',
        content: '📦 TypeScript 5.5 dropped and the type inference improvements are incredible. Inferred type predicates alone will clean up so much boilerplate in large codebases. Still writing plain JavaScript? It\'s time to migrate. #TypeScript #WebDev',
        likeCount: 76,
        dislikeCount: 3,
        createdDate: '2026-04-19',
    },
    {
        creatorName: 'Alice Chen',
        creatorEmail: 'alice@quickchat.demo',
        creatorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AliceChen',
        content: '☁️ The cloud wars are intensifying around AI infrastructure. AWS, Azure, and GCP are all racing to offer the best GPU/TPU clusters. If you\'re not designing cloud-native AI pipelines yet, your stack may be obsolete sooner than you think. #Cloud #MLOps',
        likeCount: 135,
        dislikeCount: 9,
        createdDate: '2026-04-18',
    },
    {
        creatorName: 'Bob Martinez',
        creatorEmail: 'bob@quickchat.demo',
        creatorImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BobMartinez',
        content: '🧠 Learning in public is the most underrated career move in tech. Write that blog post. Open-source that side project. Share the lesson you learned the hard way. The compounding returns on authentic visibility are real. #Career #OpenSource',
        likeCount: 189,
        dislikeCount: 2,
        createdDate: '2026-04-17',
    },
];
