version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: quickchat_postgres
    environment:
      POSTGRES_DB: quickChatDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - quickchat-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: quickchat_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - quickchat-network
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      retries: 3
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: quickchat_kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - quickchat-network
    ports:
      - "5601:5601"

  redis:
    image: redis:latest
    container_name: quickchat_redis
    ports:
      - "6379:6379"
    networks:
      - quickchat-network

  quickchat-backend:
    container_name: quickchat_backend
    build:
      context: ./quick-chat-backend/quickChat
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - elasticsearch
    environment:
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200
    networks:
      - quickchat-network
    ports:
      - "8080:8080"
    entrypoint: ["/bin/sh", "-c", "while ! curl -s http://elasticsearch:9200; do echo 'Waiting for Elasticsearch...'; sleep 2; done; exec java -jar /quickChat-0.0.1-SNAPSHOT.jar"]

  quickchat-frontend:
    container_name: quickchat_frontend
    build:
      context: ./quick-chat-client
      dockerfile: Dockerfile
    depends_on:
      - quickchat-backend
    networks:
      - quickchat-network
    ports:
      - "4200:4200"
    entrypoint: ["/bin/sh", "-c", "while ! curl -s http://quickchat-backend:8080; do echo 'Waiting for Backend...'; sleep 2; done; exec npm start"]

networks:
  quickchat-network:
    driver: bridge
