version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: quickchat_postgres
    environment:
      POSTGRES_DB: quickChatDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quickchat-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: quickchat_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - quickchat-network
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: quickchat_kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - quickchat-network
    ports:
      - "5601:5601"

  redis:
    image : redis:latest
    container_name: quickchat_redis
    ports:
      - "6379:6379"
    networks:
      - quickchat-network
    volumes:
      - redis-data:/var/lib/redis/data

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  elasticsearch-data:
    driver: local

networks:
  quickchat-network:
    driver: bridge
