'use strict';

const fs = require('fs');
const path = require('path');

const base = process.env.QUICKCHAT_API_BASE || 'http://localhost:8080';
const target = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.mkdirSync(path.dirname(target), { recursive: true });
const content = `// Auto-generated by scripts/write-env.cjs; do not edit by hand
export const environment = {
  production: true,
  apiBaseUrl: ${JSON.stringify(base)}
};
`;
fs.writeFileSync(target, content, 'utf8');
console.log('Wrote', target, 'apiBaseUrl=', base);
