spring.application.name=quickChat
spring.data.elasticsearch.cluster-nodes=localhost:9200
spring.data.elasticsearch.cluster-name=docker-cluster

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/quickChatDB
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis configuration
spring.data.redis.url=rediss://default:Jy5jIwkPYTuApVGvFGVCi5856IUU2wuh@redis-18739.c266.us-east-1-3.ec2.redns.redis-cloud.com:18739
active.user.key=activeuser
