spring.application.name=quickChat

# Elasticsearch
spring.elasticsearch.uris=${SPRING_ELASTICSEARCH_URIS:http://quickchat_elasticsearch:9200}

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://quickchat_postgres:5432/quickChatDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.redis.host=${SPRING_REDIS_HOST:quickchat_redis}
spring.redis.port=${SPRING_REDIS_PORT:6379}
spring.redis.password=${SPRING_REDIS_PASSWORD:}
spring.redis.ssl.enabled=${SPRING_REDIS_SSL:false}
spring.redis.timeout=10000
spring.redis.jedis.pool.max-active=50
spring.redis.jedis.pool.max-idle=10
spring.redis.jedis.pool.min-idle=5

# Custom
active.user.key=activeuser
