spring.application.name=quickChat

# Elasticsearch
spring.data.elasticsearch.cluster-nodes=quickchat_elasticsearch:9200

# PostgreSQL
spring.datasource.url=jdbc:postgresql://quickchat_postgres:5432/quickChatDB
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.redis.host=quickchat_redis
spring.redis.port=6379
spring.redis.timeout=10000
spring.redis.jedis.pool.max-active=50
spring.redis.jedis.pool.max-idle=10
spring.redis.jedis.pool.min-idle=5

# WebSocket
spring.websocket.message-size-limit=2MB
spring.websocket.buffer-size-limit=2MB

# Custom
active.user.key=activeuser
